name: dart_get_upto_speed
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
environment:
  sdk: ^3.0.0

# Add regular dependencies here.
dependencies:
  freezed_annotation: ^2.2.0
  meta: ^1.9.1
# path: ^1.8.0
dev_dependencies:
  build_runner: ^2.4.4
  freezed: ^2.3.4
  lint: ^2.1.2
  lints: ^2.0.0
  test: ^1.21.0
